### ISSUE TITLE
Install Unity by command line

### ISSUE THREAD

**Issue by Pedrobusou** [HouraiTeahouse/Unity-Build-Scripts#1]
Hey, I read [in this post](https://www.linkedin.com/pulse/how-get-passing-badges-your-unity-github-repository-travis-ci-taylor/)

>If you don't have unity plus or above, to my knowledge using Tavis-CI may not be possible. Unity needs a license to launch the editor, and there is currently no way to use a free license in the command line. See this. Here are links to Unity Plus and Pro. 

Did you manage to do it with a Unity free license, or are u using Plus or Pro? How (in case of Free License)?

**Comment by james7132** [comment]
We unfortunately did not get these scripts to work on public CI systems like Travis. However, if you are running your own build environment, this is a resolvable issue.

Even if you do have a Plus/Pro license, installing it repeatedly on multiple containers for CI purposes is not going to fly with their licensing system.
